name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '✨ User Stories'
    labels:
      - 'user story'
      - 'spike'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'hotfix'
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
      - 'dev task'
  - title: '🧰 Tasks'
    labels:
      - 'task'
  - title: '📦 Other'
    labels:
      - 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels: []  # For future (e.g., 'breaking')
  minor:
    labels:
      - 'user story'
      - 'enhancement'
      - 'spike'
  patch:
    labels:
      - 'bug'
      - 'hotfix'
      - 'task'
      - 'dev task'
      - 'chore'
  default: patch

exclude-labels:
  - 'skip-changelog'
