name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Enhancements'
    labels:
      - 'enhancement'
      - 'dev task'
      - 'dev process optimization'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'hotfix'
  - title: 'Tasks'
    labels:
      - 'task'

change-template: '- $CATEGORY: $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels: []  # Add major label here if needed
  minor:
    labels:
      - 'enhancement'
      - 'dev task'
      - 'dev process optimization'
  patch:
    labels:
      - 'bug'
      - 'hotfix'
      - 'task'
  default: patch

exclude-labels:
  - 'skip-changelog'
