name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ User Stories'
    labels:
      - 'user story'
      - 'spike'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'hotfix'
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
      - 'dev task'
  - title: '🧰 Tasks'
    labels:
      - 'task'
  - title: '📦 Other'
    labels:
      - 'chore'

change-template: '- $TITLE (#$NUMBER)'  # <--- No @AUTHOR here

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'user story'
      - 'enhancement'
      - 'spike'
  patch:
    labels:
      - 'bug'
      - 'hotfix'
      - 'task'
      - 'dev task'
      - 'chore'
  default: patch

template: |
  ## What’s Changed

  $CHANGES
