name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
version-resolver:
  field: semver
  default: patch
categories:
  - title: '🚀 Features'
    labels: ['enhancement', 'dev task', 'dev process optimization']
  - title: '🐛 Bug Fixes'
    labels: ['bug', 'hotfix']
  - title: '📝 Tasks'
    labels: ['task']
  - title: '🔥 Major Changes'
    labels: ['major']
template: |
  ## What's Changed
  $CHANGES
