name: Publish Draft Release

on:
  pull_request:
    types: [labeled]   # Trigger when a label is added to a PR

permissions:
  contents: write

jobs:
  publish-draft:
    if: github.event.label.name == 'publish'  # Only run if the PR label is 'publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish latest draft release
        uses: actions/github-script@v7
        with:
          script: |
            // Get all releases
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Find the latest draft release
            const draft = releases.data.find(r => r.draft);
            if (!draft) {
              core.setFailed("No draft release found to publish.");
              return;
            }

            // Publish it
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: draft.id,
              draft: false
            });

            console.log(`Draft release "${draft.tag_name}" published!`);
