name: Draft Release

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
